DROP DATABASE IF EXISTS MIAIA;
CREATE DATABASE MIAIA;
USE MIAIA;

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(40),
    APELLIDO VARCHAR(40),
    FECHA_NACIMIENTO DATE,
    CORREO_ELECTRONICO VARCHAR(100),
    CONTRASEÑA VARCHAR(50)
)