DROP DATABASE IF EXISTS MIAIA;
CREATE DATABASE MIAIA;
USE MIAIA;

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(40),
    APELLIDO VARCHAR(40),
    NOMBREUSER VARCHAR(40),
    GENERO VARCHAR(40),
    CONTRASEÑA VARCHAR(50)
)